Feature/#1 UI login
30th-THE-SOPT-iOS-Part/YangJeongYeon pull request #2
Opened 2022-04-10 14:39 UTC by jeongkite

## 🌱 작업한 내용

- 기본과제
- 도전과제 (그런데 버튼 활성화는 좀 애매함..)

## 🌱 PR Point

- <div>처럼 한 번에 묶어서 가운데 정렬이나 뭐시기 하면 좋을 것 같은데 나중에 알아봐야지..
- 회원가입 이후 마지막 페이지에서 완료하기 눌렀을 때 맨 처음 로그인 페이지로 가야하지 않나요????
- 버튼 활성화 하는 코드 어디서 주워왔는데 더 깔끔하게 짜고싶다..

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 로그인/회원가입 | ![Simulator Screen Recording - iPhone 11 - 2022-04-10 at 23 27 46](https://user-images.githubusercontent.com/75439868/162624668-57c5d7ae-d51b-4579-a8a1-91987fc041cd.gif) |

## 📮 관련 이슈

- Resolved: #1

2022-04-10 14:43 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +
요기 필요없는 빈줄은 삭제하는게 좋을 것 같습니다!

2022-04-10 14:46 UTC, jane1choi requested changes
> 리뷰 확인 부탁드립니다~

테스트에요~

~~~Swift
func hello() {
}
~~~

2022-04-10 14:46 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/SceneDelegate.swift
> +
리뷰 테스트

2022-04-10 14:46 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/SceneDelegate.swift
> +    }
요기도 테스트입니다.

2022-04-10 14:47 UTC, jane1choi approved these changes
확인했습니다!

2022-04-10 14:47 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +
확인~

2022-04-10 15:29 UTC, jimin-kiim commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +        nextBtn.isEnabled = false
생명 주기 함수 내부에는 코드들 직접 쓰는 것보다 함수로 만들어서 함수 호출하는 게 좋대영!

2022-04-10 15:32 UTC, jimin-kiim commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +                $0.text?.isEmpty
벌써 클로저 쓰는 언니 멋있엉😲👍🏻

2022-04-10 15:38 UTC, jimin-kiim commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +class FirstSignupViewController: UIViewController {
ViewController VC로 줄여서 많이 쓴대요! FirstSignUp 이해하기 쉽게 이름 잘 지은 것 같아용👍🏻👍🏻

2022-04-10 15:50 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +class FirstSignupViewController: UIViewController {
@jimin-kiim 
파일명에 대해 많은 오비분들이 ViewController -> VC로 줄여서 쓰기도 한답니다!
요렇게 코멘트 달아주신 분들이 많아서 줄여서 쓰는 것이 더 좋다!로 오해하실 수 있어서 코멘트 남기고갈게요..!
줄여서 쓰는게 더 간편하고 파일명도 짧아져서 줄여서 쓰시는 분들도 많은데
간결함보다는 명료성, 정확성이 중요하기 때문에현업에서는 줄이지 않고 쓰는 곳이 많다고 합니다! 그래서 저희 조 컨벤션도 파일명은 줄이지 않는 것으로 가져가고 있습니다!
물론 어떤 방법이 더 좋다라고 말할 순 없겠지만 약어 사용에 대해 오해하실 수 있어서 남깁니다..ㅎ

2022-04-10 15:54 UTC, jimin-kiim commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +class FirstSignupViewController: UIViewController {
답글 정말 감사합니다 🥺 조별로 컨벤션도 다르고 그런 이유가 있었군요 리뷰를 더 신중하게 달아야겠다는 반성도 하고 갑니다..ㅎㅎ!! 자세히 알려주셔서 너무 감사드립니다!!!!

2022-04-10 15:58 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +class FirstSignupViewController: UIViewController {
@jimin-kiim 
아니아니 반성 절대 노...혹싀나 지민님이 오해하실 수 있을 것 같아 남긴 코멘트니 그렇구나~정도로 참고만 해주세요!
리뷰 열심히 달아주는 모습 넘 멋집니다🔥👍🏻

2022-04-10 16:03 UTC, jimin-kiim commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +class FirstSignupViewController: UIViewController {
@jane1choi 네! 감사드려요☺️☺️

2022-04-10 16:07 UTC, jeongkite commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +        nextBtn.isEnabled = false
오 대박 글쿤요!! 하지만 저도 어디서 주워온 코드라.. 제가 멋쟁이 코드를 주워왔군요😎 언젠가 멋쟁이 코드를 스스로 짜는 날이 오길..🙏 좋은 댓글 감사합니다~~!!

2022-04-10 16:07 UTC, jeongkite commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +                $0.text?.isEmpty
하하하하하 나도 클로저 잘 쓰고 싶다...........😂😂😂

2022-04-10 16:40 UTC, jane1choi reviewed
> 비밀번호를 잊으셨나요? 외에 모든 요소가 중앙정렬인데 View 자체를 중앙정렬 해도 되는건가요? 어떤게 효율적이고 일반적인 방법인지 궁금해요!

2주차 세미나에서 AutoLayout에 대해 배웠으니 컴포넌트 레이아웃 설정에 대해 이해하셨을 것 같은데요!
레이아웃은 요소 간의 상대적 거리를 설정해주어야 하기 때문에 View자체를 중앙 정렬하는 것은 불가합니다.
컴포넌트 요소 각각 레이아웃을 설정해주어야해요!

> 가입하기 버튼이 아래와 같이 원하는 것과 다르게 떨어져 있는데 이걸 더 붙일 수 있는 방법이 있을까요?

요것도 AutoLayout을 적용하여 원하는 간격을 설정해주면 해결될 것 같습니다~!

1차 과제하느라 넘넘 수고하셨어요😊🔥

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +    }
굿굿 버튼 활성화 조건에 대한 처리 잘해주셨네요!
PR Point에 남겨주신
> 텍스트 입력시에만 버튼 활성화 하는 부분 @objc 해서 썼는데 swift로는 불가능한 기능인가요?

요 질문에 답변을 해보자면, 결론부터 말하자면 불가능하진 않습니다. 
다만 이렇게 @objc 함수를 사용해서 처리해주는게 더 효율적인 방법이라고 생각합니다!
이 함수를 쓰지 않는다면, 스토리보드에서 `textField`에 대해 editing changed와 같은 @IBAction을 연결해서도 
처리해줄 수 있을 것 같아요!
하지만, 로그인 화면과 같이 `textField`가 두 개 있는 경우에는 각각 Action을 연결하고 
버튼 활성화 조건을 판단해주는 코드를 두번써줘야하는 번거로움이 있는 것 같습니다.

그리고 `textFieldDidBeginEditing(_:)` 이라는 메서드를 사용해줄 수도 있을 것 같은데요, 
요건 UITextFieldDelegate를 채택해서 구현해주어야 합니다.
자세한 내용은 아래 공식문서와, 참고 자료 확인해주시면 될 것 같아요! 
https://developer.apple.com/documentation/uikit/uitextfielddelegate/1619590-textfielddidbeginediting
https://jaemuyeo.github.io/ios/textDelegate/

어떤 방법이 더 좋다! 라고 단정지어 말할 순 없겠지만 다양한 방법들을 시도해보면서
정연님이 생각하기에 더 효율적인 방법을 사용해서 처리하면 좋을 것 같습니다!

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +
필요없는 빈줄은 삭제해줍시다!

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +
요기두요!

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +        [usernameTextField, passwordTextField].forEach({ $0?.addTarget(self, action: #selector(editingChanged), for: .editingChanged) })
`forEach`사용해서 한번에 처리 좋습니다!
클로저 경량문법을 적용해 아래와 같이 ()는 생략하면 더 깔끔할 것 같네요!
```Swift
 [usernameTextField, passwordTextField].forEach { 
      $0?.addTarget(self, action: #selector(editingChanged), for: .editingChanged) 
}
```
그리고 생명주기 함수 안에는 코드 가독성을 위해 함수 호출만 해주는 것이 좋습니다!

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/ViewController.swift
> +
안쓰는 파일은 삭제해줍시다!

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/WelcomeViewController.swift
> +
요기도 빈줄 삭제해줍시다~!

2022-04-10 16:40 UTC, jane1choi commented on Instagram-CloneCoding/Instagram-CloneCoding/WelcomeViewController.swift
> +        }
깔끔한 코드 굳굳👍🏻
함수화해서 `viewDidLoad()`에서 호출하는 것까지 너무 잘하셨네요!!

2022-04-11 01:46 UTC, yujindonut commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +        [usernameTextField, passwordTextField].forEach({ $0?.addTarget(self, action: #selector(editingChanged), for: .editingChanged) })
for each구문 사용해서 하는 코드 줍줍해가요~!~!,,,,

2022-04-11 04:42 UTC, Jihyun247 commented
> 가입하기 버튼이 아래와 같이 원하는 것과 다르게 떨어져 있는데 이걸 더 붙일 수 있는 방법이 있을까요?

계정이 없으신가요? UILabel과 가입하기 UIButton을 StackView로 묶은 것 같은데 맞나용 ? 맞다면 스택뷰 width나 spacing을 줄여보세요 !

2022-04-11 04:44 UTC, Jihyun247 commented on Instagram-CloneCoding/Instagram-CloneCoding/Base.lproj/Main.storyboard
> +                            <stackView opaque="NO" contentMode="scaleToFill" translatesAutoresizingMaskIntoConstraints="NO" id="JTd-j8-L4i">
> 가입하기 버튼이 아래와 같이 원하는 것과 다르게 떨어져 있는데 이걸 더 붙일 수 있는 방법이 있을까요?
'계정이 없으신가요?' UILabel과 '가입하기' UIButton을 StackView로 묶은 것 같은데 맞나용 ? 맞다면 스택뷰 width나 spacing을 줄여보세요 !

2022-04-11 11:09 UTC, jeongkite commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +        [usernameTextField, passwordTextField].forEach({ $0?.addTarget(self, action: #selector(editingChanged), for: .editingChanged) })
히히힣 저도 줍줍해온 코드..~~ 감삼다~!!😎

2022-04-11 12:04 UTC, 513sojin approved these changes

2022-04-11 12:04 UTC, 513sojin commented on Instagram-CloneCoding/Instagram-CloneCoding/FirstSignupViewController.swift
> +        nextBtn.isEnabled = !(usernameTextField.text?.isEmpty ?? true)
버튼 활성화 조건 처리를 요렇게 깔끔하게도 할 수 있는거군요 !! 한 수 배워갑니다 ㅎㅎ

2022-04-11 12:04 UTC, 513sojin commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +        loginBtn.isEnabled = false
저도 요런 친구들 viewDidLoad함수 안에다가 작성해줬는데 같이 함수로 빼는 작업을 해보아요 💪🏻

2022-04-11 14:04 UTC, lee-euijin commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +                $0.text?.isEmpty
이렇게 깔끔하게 줄여쓸 수 있구만요... 한 번 다음 과제 때 적용해봐야겠어용!

2022-04-11 14:10 UTC, lee-euijin commented on Instagram-CloneCoding/Instagram-CloneCoding/LoginViewController.swift
> +        [usernameTextField, passwordTextField].forEach({ $0?.addTarget(self, action: #selector(editingChanged), for: .editingChanged) })
저도 주워가요!!~~

2022-04-12 14:01 UTC, lee-euijin commented
풀리 알람 확인!

2022-04-12 14:04 UTC, lee-euijin commented
한번 더!

2022-04-12 14:05 UTC, SuwonPabby commented
두번 더!

2022-04-20 17:38 UTC, merged